openapi: 3.0.0
info:
  title: Devloom - Programming Education
  description: Devloom is a modular, scalable API designed for building a modern programming education platform. Built with TypeScript + Express + MongoDB + Zod, focusing on clarity, structure, and longâ€‘term maintainability.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1/
    description: base url
tags:
  - name: Auth
    description: User Auth
  - name: Category
    description: category of courses
  - name: Course
    description: courses
  - name: Lesson
    description: lessons of Course
paths:
  /auth/signup:
    post:
      operationId: createUser
      summary: create new user
      description: Create a new user in db collection(users)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: user created successfully
          content:
            application/json:
              example:
                ok: true
                message: Sign up successfully
                user:
                  id: 695d0babedf79cffd1f83999
                  name: john
                  email: john@mail.co
                  createdAt: '2026-01-19T19:22:20.707Z'
                  updatedAt: '2026-01-19T19:22:20.707Z'
                  role: USER
  /auth/login:
    post:
      operationId: login
      summary: login users
      description: login user with email and password
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: user logged in successfully
          content:
            application/json:
              example:
                ok: true
                message: Login successfully
                user:
                  accessToken: 121hasjfhajfh12
                  id: 695d0babedf79cffd1f83999
                  name: john
                  email: john@mail.co
                  createdAt: '2026-01-19T19:22:20.707Z'
                  updatedAt: '2026-01-19T19:22:20.707Z'
                  role: USER
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
      description: 'accessToken Authorization: Bearer <accessToken>'
  schemas:
    SignupRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
          description: name must be at least 3 characters and less than 20 characters
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
          pattern: /^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$/
          description: password must be at least 6 characters and contain at least one letter and one number
      required:
        - email
        - password
      example:
        name: john
        email: john@mail.co
        password: 123qwe
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
          pattern: /^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$/
          description: password must be at least 6 characters and contain at least one letter and one number
      required:
        - email
        - password
      example:
        email: john@mail.co
        password: 123qwe
